### ISSUE TITLE
More iterations leads to small surfaces

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/ch-shrinkwrap#18]
I'm currently testing the state of the shrink-wrapping on the vector_vis branch. I noticed that the higher I set "max_iters", the smaller the resulting surface. I think this may have always been the case, but I didn't really think about it before. Is this expected behavior? I thought high max_iters was just supposed to refine the surface, not necessarily consistently shrink it more. Here's an example of what I mean:

Parameters: 
Max_iters: variable
Curvature weight: 40
Remesh Frequency: 5
Neck first iter: 0
Punch frequency: 0
Kc: 1.0
Minimum edge length: -1
Smooth curvature: True
Truncate at: 1000

with Max iters = 19
![image](https://user-images.githubusercontent.com/36608397/209564147-4d51e152-e972-4f95-8287-76187b51d3f3.png)
![image](https://user-images.githubusercontent.com/36608397/209564306-6bd80f35-f9ae-413c-9673-400bb7fd2df9.png)

with Max iters = 39
![image](https://user-images.githubusercontent.com/36608397/209564242-1c12fc63-6bdb-4e9d-b461-7b00a6b05b77.png)
![image](https://user-images.githubusercontent.com/36608397/209564271-29c1b1d8-3994-4803-9c10-8cab824ed822.png)

with Max iters = 79
![image](https://user-images.githubusercontent.com/36608397/209564494-156276a7-8a60-47c6-92d4-325b5448cd5d.png)
![image](https://user-images.githubusercontent.com/36608397/209564529-ed0f8918-9105-4142-a5dd-c35af4defbc2.png)

As you can see, things get real weird at Max iters = 79. I would expect to see this behavior when changing Curvature weight or Kc, but not for Max iters. Perhaps, I misunderstand the parameter, but I thought I'd bring this up just in case.

**Comment by zacsimile** [comment]
I believe we have effectively fixed this with the new curvature force. We can go well beyond 40 iterations without pulling the mesh in. OK to close @lukasfue ?

**Comment by lukasfue** [comment]
I haven't been able to test the new curvature force but I'm guessing it behaves different enough that this is no longer relevant anyways.
